/**
 * SCORY — data.js
 * Donnees projets et themes visuels (bilingue FR/EN).
 */

/** Projets bilingues */
export const PROJECTS = {
  fr: [
    { title: "Portfolio Scory", hook: "JS · Python · Agents IA. Forme a 42. Disponible partout.", desc: "Developpeur full-stack JS & Python, forme a 42. Je construis des produits complets.", detail: "Developpeur full-stack JS & Python, forme a 42. Je construis des produits complets — du schema Postgres aux agents IA — et je me deplace la ou le projet en a besoin. Long terme : IA engineer. Aujourd'hui : le dev qui sort ca en prod, seul. Naviguez entre les disques pour decouvrir mes realisations. Chaque projet a sa propre decision technique. Si un projet vous parle, lancez le bot en bas — 5 questions, je vous recontacte.", stack: ["Three.js","GLSL","GSAP","Vanilla JS"], url: null, screenshots: [] },
    { title: "4dayvelopment", hook: "Pour les sites vitrine, j'ai une agence. Ce n'est pas ce dont je parle ici.", desc: "Agence web sur-mesure — design dark luxury, WebGL maison, zero template.", detail: "Vous voulez un site qui vous distingue, pas un template Wix repeint. 4Dayvelopment livre des ecosystemes digitaux complets : branding, site sur-mesure, automations n8n, funnel de conversion. Design dark luxury avec curseur magnetique, WebGL maison sans Three.js, mode sombre/clair, formulaire intelligent qui genere un devis instantane.", stack: ["Node.js","WebGL","GSAP","n8n","Zod"], url: "https://4dayvelopment.fr/", screenshots: ["./image/fond4Day.jpg","./image/4dayMobile.jpg"] },
    { title: "JIMMY", hook: "12 000 lignes de TypeScript strict. Zero dependance. Zero framework.", desc: "Experience narrative IA + arene de combat temps reel — TypeScript strict, 12 000 lignes.", detail: "JIMMY combine roman d'horreur dark (20 000 mots, 3 arcs) et jeu interactif. Combats generes en temps reel par Gemini Pro. Permadeath total. Concept canon : un jour, un vrai joueur tuera Scory, le protagoniste, et son nom rentrera dans le roman. 30 demons avec hierarchie evolutive, 130 evenements narratifs, boutique de 44 artefacts. 12 000 lignes de TypeScript strict — ce qu'on peut livrer en solo quand on maitrise la stack de bout en bout.", stack: ["Three.js","Gemini Pro","TypeScript","Canvas API","PWA","Vanilla JS"], url: "https://splendid-malasada-e630ad.netlify.app/", caseStudy: "jimmy", screenshots: [] },
    { title: "DYG", hook: "Scoring côté serveur. Un score manipulable côté client ne vaut rien.", desc: "Scanner de profil GitHub — score 8 axes, archétype, conseils. Back-end Fastify + PostgreSQL.", detail: "Outil web qui scanne un profil GitHub et renvoie, en quelques secondes, un score sur 8 axes, un archétype de développeur et des conseils concrets — sans inscription. Côté technique : front en vanilla JS, back en Fastify 5 + PostgreSQL, authentification GitHub OAuth (JWT HttpOnly + AES-256-GCM), scoring calculé côté serveur pour qu'aucun score ne soit manipulable, déployé via Docker. Une plateforme plus large (entraînement, projets en équipe) est en développement.", stack: ["Vanilla JS","Fastify 5","PostgreSQL","GitHub OAuth","JWT + AES","Docker"], url: "https://dyg-olfu.onrender.com", caseStudy: "dyg", screenshots: [] },
    { title: "Lyma", hook: "Rate-limit ? Le provider suivant configuré prend le relais.", desc: "Agent codeur CLI multi-provider — rotation des clés, fallback entre providers.", detail: "Agent de code en ligne de commande, multi-provider LLM (Anthropic, OpenAI, DeepSeek, Qwen, Kimi, ou tout serveur local compatible OpenAI). Plusieurs clés par provider en round-robin sur rate-limit ou erreur 5xx ; si un provider est indisponible, le suivant configuré prend le relais. Pont natif vers agent-factory pour compiler et exécuter des sous-agents bornés. Blacklist de sécurité non désactivable. Campagne sécurité octobre 2026 : sandbox des agents compilés, gate lyma approve.", stack: ["Python","Multi-LLM","Anthropic","OpenAI","DeepSeek","agent-factory"], url: null, caseStudy: "lyma", screenshots: [] },
  ],
  en: [
    { title: "Scory Portfolio", hook: "JS · Python · AI Agents. Trained at 42. Available anywhere.", desc: "Full-stack JS & Python developer, trained at 42. I ship complete products.", detail: "Full-stack JS & Python developer, trained at 42. I build complete products — from Postgres schemas to AI agents — and go wherever the project needs me. Long term: AI engineer. Today: the dev who ships this solo, in production. Browse the discs to see my work. Each project has a concrete technical decision behind it. If something catches your eye, launch the bot — 5 questions, I'll get back to you.", stack: ["Three.js","GLSL","GSAP","Vanilla JS"], url: null, screenshots: [] },
    { title: "4dayvelopment", hook: "For websites, I have an agency. That's not what I'm talking about here.", desc: "Bespoke web agency — dark luxury design, in-house WebGL, zero templates.", detail: "You want a site that stands out — not a repainted Wix template. 4Dayvelopment delivers complete digital ecosystems: branding, custom site, n8n automations, conversion funnel. Dark luxury design with magnetic cursor, in-house WebGL without Three.js, dark/light mode, smart form generating instant quotes.", stack: ["Node.js","WebGL","GSAP","n8n","Zod"], url: "https://4dayvelopment.fr/", screenshots: ["./image/fond4Day.jpg","./image/4dayMobile.jpg"] },
    { title: "JIMMY", hook: "12,000 lines of strict TypeScript. Zero dependencies. Zero frameworks.", desc: "AI-driven narrative experience + real-time combat arena — strict TypeScript, 12k lines.", detail: "JIMMY blends a dark horror novel (20,000 words, 3 arcs) with interactive gameplay. Real-time combat generated by Gemini Pro. Total permadeath. Canon concept: one day, a real player will kill Scory and their name will enter the novel. 30 demons, 130 narrative events, 44-artifact marketplace. 12,000 lines of strict TypeScript — proof of what can be shipped solo when you master the stack end-to-end.", stack: ["Three.js","Gemini Pro","TypeScript","Canvas API","PWA","Vanilla JS"], url: "https://splendid-malasada-e630ad.netlify.app/", caseStudy: "jimmy", screenshots: [] },
    { title: "DYG", hook: "Server-side scoring. A client-side score is worthless.", desc: "GitHub profile scanner — 8-axis score, archetype, advice. Fastify + PostgreSQL back-end.", detail: "Web tool that scans a GitHub profile and returns, in seconds, an 8-axis score, a developer archetype and concrete advice — no sign-up. Under the hood: vanilla JS front-end, Fastify 5 + PostgreSQL back-end, GitHub OAuth auth (HttpOnly JWT + AES-256-GCM), scoring computed server-side so no score can be tampered with, deployed via Docker. A broader platform (training, team projects) is in development.", stack: ["Vanilla JS","Fastify 5","PostgreSQL","GitHub OAuth","JWT + AES","Docker"], url: "https://dyg-olfu.onrender.com", caseStudy: "dyg", screenshots: [] },
    { title: "Lyma", hook: "Rate-limit? The next configured provider takes over.", desc: "Multi-provider CLI coding agent — key rotation, provider fallback.", detail: "Command-line coding agent, multi-provider LLM (Anthropic, OpenAI, DeepSeek, Qwen, Kimi, or any local OpenAI-compatible server). Multiple keys per provider in round-robin on rate-limit or 5xx errors; if a provider is unavailable, the next configured one takes over. Native bridge to agent-factory to compile and run bounded sub-agents. Non-disableable security blacklist. October 2026 security campaign: compiled agent sandbox, lyma approve gate.", stack: ["Python","Multi-LLM","Anthropic","OpenAI","DeepSeek","agent-factory"], url: null, caseStudy: "lyma", screenshots: [] },
  ],
};

/** Themes visuels (identiques pour les 2 langues) */
export const THEMES = [
  { gold:"#c9a962",amber:"#e8b86d",ice:"#9ec8ff",magenta:"#c084fc",glow:"rgba(201,169,98,0.12)",glowStrong:"rgba(201,169,98,0.25)",glowDisc:"rgba(201,169,98,0.12)",fontDisplay:"'Cormorant Garamond','Times New Roman',serif",fontSans:"'DM Sans',system-ui,sans-serif",neuralFilter:"none",particleColors:[[201,169,98],[158,200,255],[192,132,252],[232,184,109],[245,242,255]] },
  { gold:"#DA5426",amber:"#f2b13b",ice:"#884083",magenta:"#DA5426",glow:"rgba(218,84,38,0.12)",glowStrong:"rgba(218,84,38,0.25)",glowDisc:"rgba(218,84,38,0.15)",fontDisplay:"'Syne',system-ui,sans-serif",fontSans:"'Inter',system-ui,sans-serif",neuralFilter:"hue-rotate(-30deg) saturate(1.8) brightness(1.15) contrast(1.1)",particleColors:[[218,84,38],[242,177,59],[136,64,131],[240,240,240],[255,160,80]] },
  { gold:"#c41e3a",amber:"#8b1a1a",ice:"#2a6fdb",magenta:"#c41e3a",glow:"rgba(196,30,58,0.12)",glowStrong:"rgba(196,30,58,0.25)",glowDisc:"rgba(196,30,58,0.20)",fontDisplay:"'Cinzel','Times New Roman',serif",fontSans:"'EB Garamond',Georgia,serif",neuralFilter:"hue-rotate(-10deg) saturate(1.6) brightness(0.9) contrast(1.3)",particleColors:[[196,30,58],[139,26,26],[42,111,219],[212,197,169],[80,20,20]] },
  { gold:"#3B82F6",amber:"#22C55E",ice:"#A855F7",magenta:"#EC4899",glow:"rgba(59,130,246,0.12)",glowStrong:"rgba(59,130,246,0.25)",glowDisc:"rgba(59,130,246,0.18)",fontDisplay:"'Bebas Neue','Cinzel',sans-serif",fontSans:"'Inter',system-ui,sans-serif",neuralFilter:"hue-rotate(200deg) saturate(1.5) brightness(1.1) contrast(1.1)",particleColors:[[59,130,246],[34,197,94],[245,197,66],[168,85,247],[236,72,153]] },
  { gold:"#c9a962",amber:"#9ec8ff",ice:"#9ec8ff",magenta:"#c9a962",glow:"rgba(158,200,255,0.1)",glowStrong:"rgba(158,200,255,0.22)",glowDisc:"rgba(158,200,255,0.2)",fontDisplay:"'JetBrains Mono','Courier New',monospace",fontSans:"'DM Sans',system-ui,sans-serif",neuralFilter:"hue-rotate(175deg) saturate(1.4) brightness(1.15)",particleColors:[[158,200,255],[201,169,98],[14,165,233],[245,242,255],[80,160,255]] },
];

