/**
 * SCORY — data.js
 * Donnees projets et themes visuels (bilingue FR/EN).
 */

/** Projets bilingues */
export const PROJECTS = {
  fr: [
    { title: "Portfolio Scory", hook: "JS · Python · Agents IA. Forme a 42. Disponible partout.", desc: "Developpeur full-stack JS & Python, forme a 42. Je construis des produits complets.", detail: "Developpeur full-stack JS & Python, forme a 42. Je construis des produits complets — du schema Postgres aux agents IA — et je me deplace la ou le projet en a besoin. Long terme : IA engineer. Aujourd'hui : le dev qui sort ca en prod, seul. Naviguez entre les disques pour decouvrir mes realisations. Chaque projet a sa propre decision technique. Si un projet vous parle, lancez le bot en bas — 5 questions, je vous recontacte.", stack: ["Three.js","GLSL","GSAP","Vanilla JS"], url: null, screenshots: [] },
    { title: "4dayvelopment", hook: "Pour les sites vitrine, j'ai une agence. Ce n'est pas ce dont je parle ici.", desc: "Agence web sur-mesure — design dark luxury, WebGL maison, zero template.", detail: "Vous voulez un site qui vous distingue, pas un template Wix repeint. 4Dayvelopment livre des ecosystemes digitaux complets : branding, site sur-mesure, automations n8n, funnel de conversion. Design dark luxury avec curseur magnetique, WebGL maison sans Three.js, mode sombre/clair, formulaire intelligent qui genere un devis instantane.", stack: ["Node.js","WebGL","GSAP","n8n","Zod"], url: "https://4dayvelopment.fr/", screenshots: ["./image/fond4Day.jpg","./image/4dayMobile.jpg"] },
    { title: "Clara Martinez", hook: "Direction artistique premium. Aurora borealis en Canvas, glassmorphism, bento grid.", desc: "Site vitrine luxe pour coach business — direction artistique sur-mesure, conversion calee.", detail: "Clara est coach business a Paris. Ses concurrentes ont des sites Wix. Solution : un site dark luxe avec aurora borealis interactive en Canvas, glassmorphism, bento grid, curseur magnetique. Le visiteur sent immediatement le premium. Direction artistique complete livree.", stack: ["HTML5","Canvas API","Vanilla JS","Lucide Icons","Aurora BG"], url: "https://clara-martinez-project.vercel.app/", screenshots: ["./image/fondClara.jpg","./image/claramartinezMobile.jpg"] },
    { title: "JIMMY", hook: "12 000 lignes de TypeScript strict. Zero dependance. Zero framework.", desc: "Experience narrative IA + arene de combat temps reel — TypeScript strict, 12 000 lignes.", detail: "JIMMY combine roman d'horreur dark (20 000 mots, 3 arcs) et jeu interactif. Combats generes en temps reel par Gemini Pro. Permadeath total. Concept canon : un jour, un vrai joueur tuera Scory, le protagoniste, et son nom rentrera dans le roman. 30 demons avec hierarchie evolutive, 130 evenements narratifs, boutique de 44 artefacts. 12 000 lignes de TypeScript strict — ce qu'on peut livrer en solo quand on maitrise la stack de bout en bout.", stack: ["Three.js","Gemini Pro","TypeScript","Canvas API","PWA","Vanilla JS"], url: "https://splendid-malasada-e630ad.netlify.app/", screenshots: ["./image/fondJimmy.png","./image/jimmyMobile.png"] },
    { title: "DYG", hook: "Scoring server-only. Un score manipulable cote client ne vaut rien.", desc: "Plateforme SaaS full-stack — 36 tables Postgres, scoring algorithmique, CI/CD, Docker.", detail: "Plateforme complete pour developpeurs. Scan GitHub, scoring sur 8 piliers, formation d'equipes en synergie, projets collaboratifs. Fastify 5, PostgreSQL avec 36 tables, JWT + AES-256-GCM, Helmet, rate-limit, Pino structured logging, Docker multistage, CI GitHub Actions, 3 suites de tests d'integration. La stack qu'on retrouve en startup serie A.", stack: ["Fastify 5","PostgreSQL","Docker","JWT + AES","Gemini API","CI / Tests"], url: "https://dyg-olfu.onrender.com", screenshots: ["./image/fondDyg.jpg","./image/dygMobile.jpg"] },
    { title: "SecurEats", hook: "Crypto Web native. Pas du bcrypt copie de Stack Overflow.", desc: "Ecosysteme fast-food 2-en-1 — PWA installable + site vitrine, cryptographie AES-256 native.", detail: "PWA installable iOS/Android sans passer par un store — chaque commande verifiee par QR code chiffre AES-256-GCM avec PBKDF2 cote client. Zero confusion possible entre restaurant, livreur et client. Performance quasi-instantanee, service worker, Content Security Policy stricte. La crypto Web native maitrisee.", stack: ["Vanilla JS","PWA","Service Worker","QR Code","Web Crypto","CSP","Video BG"], url: "https://secure-eats.vercel.app/", urlSite: "https://secure-site-weld.vercel.app/#", screenshots: ["./image/fondSecurEats.jpg","./image/secureatsMobile.jpg"] },
    { title: "agent-factory", hook: "Un agent enfant ne peut pas depasser son parent. Verifie a la compilation.", desc: "Compilateur d'agents IA bornes — capacites limitees par contrat, budgets, kill-switches, 86 tests.", detail: "CLI Python qui compile des agents IA bornes a partir d'une mission JSON ou YAML. La factory produit un dossier d'artefacts autonome : prompt systeme, configuration, outils, runner, tests. Principe fondamental : les capacites d'un agent enfant ne peuvent jamais depasser celles de son parent — verifie a la compilation, pas a l'execution. 86 tests pytest en 6 modules. Un LIMITS.md documente explicitement ce qui n'est pas implemente. Codes de sortie explicites : 0 OK · 2 BLOCKED · 3 BUDGET_EXHAUSTED · 4 KILLED.", stack: ["Python 3.11","pytest","JSON / YAML","Agents IA","Kill-switch","Securite"], url: null, screenshots: [] },
    { title: "Lyma", hook: "Rate-limit ? Le provider suivant prend le relais. Automatiquement.", desc: "Agent codeur CLI multi-provider — rotation automatique des cles, fallback inter-providers.", detail: "Agent de code en ligne de commande, multi-provider LLM (Anthropic, OpenAI, DeepSeek, Qwen, Kimi, ou tout serveur local compatible OpenAI). Plusieurs cles par provider en round-robin sur rate-limit ou erreur 5xx. Si un provider tombe, le suivant prend le relais — zero interruption. Pont natif vers agent-factory. Blacklist de securite non desactivable. Campagne securite octobre 2026 : sandbox des agents compiles, gate lyma approve.", stack: ["Python","Multi-LLM","Anthropic","OpenAI","DeepSeek","agent-factory"], url: null, screenshots: [] },
  ],
  en: [
    { title: "Scory Portfolio", hook: "JS · Python · AI Agents. Trained at 42. Available anywhere.", desc: "Full-stack JS & Python developer, trained at 42. I ship complete products.", detail: "Full-stack JS & Python developer, trained at 42. I build complete products — from Postgres schemas to AI agents — and go wherever the project needs me. Long term: AI engineer. Today: the dev who ships this solo, in production. Browse the discs to see my work. Each project has a concrete technical decision behind it. If something catches your eye, launch the bot — 5 questions, I'll get back to you.", stack: ["Three.js","GLSL","GSAP","Vanilla JS"], url: null, screenshots: [] },
    { title: "4dayvelopment", hook: "For websites, I have an agency. That's not what I'm talking about here.", desc: "Bespoke web agency — dark luxury design, in-house WebGL, zero templates.", detail: "You want a site that stands out — not a repainted Wix template. 4Dayvelopment delivers complete digital ecosystems: branding, custom site, n8n automations, conversion funnel. Dark luxury design with magnetic cursor, in-house WebGL without Three.js, dark/light mode, smart form generating instant quotes.", stack: ["Node.js","WebGL","GSAP","n8n","Zod"], url: "https://4dayvelopment.fr/", screenshots: ["./image/fond4Day.jpg","./image/4dayMobile.jpg"] },
    { title: "Clara Martinez", hook: "Premium art direction. Interactive Canvas aurora, glassmorphism, bento grid.", desc: "Luxe showcase site for business coach — bespoke art direction, conversion dialed in.", detail: "Clara is a Paris-based business coach. Her competitors use Wix sites. Solution: a dark luxe site with interactive Canvas aurora borealis, glassmorphism, bento grid, magnetic cursor. Visitors immediately feel the premium. Full art direction delivered.", stack: ["HTML5","Canvas API","Vanilla JS","Lucide Icons","Aurora BG"], url: "https://clara-martinez-project.vercel.app/", screenshots: ["./image/fondClara.jpg","./image/claramartinezMobile.jpg"] },
    { title: "JIMMY", hook: "12,000 lines of strict TypeScript. Zero dependencies. Zero frameworks.", desc: "AI-driven narrative experience + real-time combat arena — strict TypeScript, 12k lines.", detail: "JIMMY blends a dark horror novel (20,000 words, 3 arcs) with interactive gameplay. Real-time combat generated by Gemini Pro. Total permadeath. Canon concept: one day, a real player will kill Scory and their name will enter the novel. 30 demons, 130 narrative events, 44-artifact marketplace. 12,000 lines of strict TypeScript — proof of what can be shipped solo when you master the stack end-to-end.", stack: ["Three.js","Gemini Pro","TypeScript","Canvas API","PWA","Vanilla JS"], url: "https://splendid-malasada-e630ad.netlify.app/", screenshots: ["./image/fondJimmy.png","./image/jimmyMobile.png"] },
    { title: "DYG", hook: "Server-only scoring. A client-side score is worthless.", desc: "Full-stack SaaS platform — 36 Postgres tables, algorithmic scoring, CI/CD, Docker.", detail: "Complete developer platform. GitHub scan, 8-pillar scoring, complementary team formation, collaborative projects. Fastify 5, PostgreSQL with 36 tables, JWT + AES-256-GCM, Helmet, rate-limit, Pino structured logging, Docker multistage, GitHub Actions CI, 3 integration test suites. The stack you find in Series A startups.", stack: ["Fastify 5","PostgreSQL","Docker","JWT + AES","Gemini API","CI / Tests"], url: "https://dyg-olfu.onrender.com", screenshots: ["./image/fondDyg.jpg","./image/dygMobile.jpg"] },
    { title: "SecurEats", hook: "Native Web Crypto. Not bcrypt copied from Stack Overflow.", desc: "2-in-1 fast-food ecosystem — installable PWA + showcase site, native AES-256 cryptography.", detail: "Installable PWA (iOS/Android, no app store) — every order verified via AES-256-GCM encrypted QR code with client-side PBKDF2. Zero confusion between restaurant, courier and customer. Near-instant load, service worker, strict Content Security Policy. Native Web Crypto mastered.", stack: ["Vanilla JS","PWA","Service Worker","QR Code","Web Crypto","CSP","Video BG"], url: "https://secure-eats.vercel.app/", urlSite: "https://secure-site-weld.vercel.app/#", screenshots: ["./image/fondSecurEats.jpg","./image/secureatsMobile.jpg"] },
    { title: "agent-factory", hook: "A child agent can never exceed its parent. Enforced at compile time.", desc: "Bounded AI agent compiler — capabilities capped by contract, budgets, kill-switches, 86 tests.", detail: "Python CLI compiling bounded AI agents from a JSON or YAML mission file. Produces a self-contained artifact folder: system prompt, config, tools, runner, tests. Core principle: a child agent's capabilities can never exceed its parent's — checked at compile time, not runtime. 86 pytest tests across 6 modules. A LIMITS.md documents what is not implemented. Explicit exit codes: 0 OK · 2 BLOCKED · 3 BUDGET_EXHAUSTED · 4 KILLED.", stack: ["Python 3.11","pytest","JSON / YAML","AI Agents","Kill-switch","Security"], url: null, screenshots: [] },
    { title: "Lyma", hook: "Rate-limit? The next provider takes over. Automatically.", desc: "Multi-provider CLI coding agent — automatic key rotation, inter-provider fallback.", detail: "Command-line coding agent, multi-provider LLM (Anthropic, OpenAI, DeepSeek, Qwen, Kimi, or any local OpenAI-compatible server). Multiple keys per provider in round-robin on rate-limit or 5xx errors. If a provider goes down, the next takes over — zero interruption. Native bridge to agent-factory. Non-disableable security blacklist. Security campaign October 2026: compiled agent sandbox, lyma approve gate.", stack: ["Python","Multi-LLM","Anthropic","OpenAI","DeepSeek","agent-factory"], url: null, screenshots: [] },
  ],
};

/** Themes visuels (identiques pour les 2 langues) */
export const THEMES = [
  { gold:"#c9a962",amber:"#e8b86d",ice:"#9ec8ff",magenta:"#c084fc",glow:"rgba(201,169,98,0.12)",glowStrong:"rgba(201,169,98,0.25)",glowDisc:"rgba(201,169,98,0.12)",fontDisplay:"'Cormorant Garamond','Times New Roman',serif",fontSans:"'DM Sans',system-ui,sans-serif",neuralFilter:"none",particleColors:[[201,169,98],[158,200,255],[192,132,252],[232,184,109],[245,242,255]] },
  { gold:"#DA5426",amber:"#f2b13b",ice:"#884083",magenta:"#DA5426",glow:"rgba(218,84,38,0.12)",glowStrong:"rgba(218,84,38,0.25)",glowDisc:"rgba(218,84,38,0.15)",fontDisplay:"'Syne',system-ui,sans-serif",fontSans:"'Inter',system-ui,sans-serif",neuralFilter:"hue-rotate(-30deg) saturate(1.8) brightness(1.15) contrast(1.1)",particleColors:[[218,84,38],[242,177,59],[136,64,131],[240,240,240],[255,160,80]] },
  { gold:"#C9A84C",amber:"#E8D49A",ice:"#C9A84C",magenta:"#A8863A",glow:"rgba(201,168,76,0.12)",glowStrong:"rgba(201,168,76,0.25)",glowDisc:"rgba(201,168,76,0.18)",fontDisplay:"'Playfair Display','Times New Roman',serif",fontSans:"'Inter',system-ui,sans-serif",neuralFilter:"hue-rotate(85deg) saturate(1.6) brightness(1.2) contrast(1.05)",particleColors:[[201,168,76],[232,212,154],[168,134,58],[245,240,232],[180,155,90]] },
  { gold:"#c41e3a",amber:"#8b1a1a",ice:"#2a6fdb",magenta:"#c41e3a",glow:"rgba(196,30,58,0.12)",glowStrong:"rgba(196,30,58,0.25)",glowDisc:"rgba(196,30,58,0.20)",fontDisplay:"'Cinzel','Times New Roman',serif",fontSans:"'EB Garamond',Georgia,serif",neuralFilter:"hue-rotate(-10deg) saturate(1.6) brightness(0.9) contrast(1.3)",particleColors:[[196,30,58],[139,26,26],[42,111,219],[212,197,169],[80,20,20]] },
  { gold:"#3B82F6",amber:"#22C55E",ice:"#A855F7",magenta:"#EC4899",glow:"rgba(59,130,246,0.12)",glowStrong:"rgba(59,130,246,0.25)",glowDisc:"rgba(59,130,246,0.18)",fontDisplay:"'Bebas Neue','Cinzel',sans-serif",fontSans:"'Inter',system-ui,sans-serif",neuralFilter:"hue-rotate(200deg) saturate(1.5) brightness(1.1) contrast(1.1)",particleColors:[[59,130,246],[34,197,94],[245,197,66],[168,85,247],[236,72,153]] },
  { gold:"#f2b13b",amber:"#DA5426",ice:"#c41e3a",magenta:"#f2b13b",glow:"rgba(242,177,59,0.12)",glowStrong:"rgba(242,177,59,0.25)",glowDisc:"rgba(242,177,59,0.18)",fontDisplay:"'Syne',system-ui,sans-serif",fontSans:"'Inter',system-ui,sans-serif",neuralFilter:"hue-rotate(-20deg) saturate(1.6) brightness(1.1) contrast(1.15)",particleColors:[[242,177,59],[218,84,38],[196,30,58],[255,215,120],[240,192,64]] },
  { gold:"#60A5FA",amber:"#38BDF8",ice:"#0EA5E9",magenta:"#7C3AED",glow:"rgba(96,165,250,0.1)",glowStrong:"rgba(96,165,250,0.22)",glowDisc:"rgba(96,165,250,0.18)",fontDisplay:"'JetBrains Mono','Courier New',monospace",fontSans:"'DM Sans',system-ui,sans-serif",neuralFilter:"hue-rotate(200deg) saturate(1.5) brightness(1.1)",particleColors:[[96,165,250],[56,189,248],[14,165,233],[124,58,237],[200,220,255]] },
  { gold:"#c9a962",amber:"#9ec8ff",ice:"#9ec8ff",magenta:"#c9a962",glow:"rgba(158,200,255,0.1)",glowStrong:"rgba(158,200,255,0.22)",glowDisc:"rgba(158,200,255,0.2)",fontDisplay:"'JetBrains Mono','Courier New',monospace",fontSans:"'DM Sans',system-ui,sans-serif",neuralFilter:"hue-rotate(175deg) saturate(1.4) brightness(1.15)",particleColors:[[158,200,255],[201,169,98],[14,165,233],[245,242,255],[80,160,255]] },
];

